datagrid:
    issues-grid:
        pageTitle: andy.bugtrack.issue.report
        source:
            extended_entity_name: %issue.entity.class%
            acl_resource: issue_view
            type: orm
            query:
                select:
                    - distinct issue.id
                    - issue.code
                    - issue.summary
                    - type_enum.name as type
                    - priority.name as priorityName
                    - resolution.name as resolutionName
                    - assignee.id as assigneeId
                    - CONCAT(assignee.firstName, ' ', assignee.lastName) as assigneeFullName
                    - reporter.id as reporterId
                    - CONCAT(reporter.firstName, ' ', reporter.lastName) as reporterFullName
                    - issue.createdAt
                    - issue.updatedAt
                    - workflow_step.label as step
                from:
                    - { table: AndyBugTrackBundle:Issue, alias: issue }
                join:
                    left:
                        - { join: issue.type, alias: type_enum }
                        - { join: issue.priority, alias: priority }
                        - { join: issue.resolution, alias: resolution }
                        - { join: issue.assignee, alias: assignee }
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.collaborators, alias: collaborators }
                        - { join: issue.workflowStep, alias: workflow_step }
        columns:
            code:
                label: andy.bugtrack.issue.code.label
            summary:
                label: andy.bugtrack.issue.summary.label
            type:
                label: andy.bugtrack.issue.type.label
            priorityName:
                label: andy.bugtrack.issue.priority.label
            resolutionName:
                label: andy.bugtrack.issue.resolution.label
            reporterFullName:
                label: andy.bugtrack.issue.reporter.label
            assigneeFullName:
                label: andy.bugtrack.issue.assignee.label
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
            collaborators:
                label: andy.bugtrack.issue.collaborators.label
                renderable: false
            step:
                label: andy.bugtrack.issue.workflow_step.label
        sorters:
            columns:
                code:
                    data_name: issue.code
                summary:
                    data_name: issue.summary
                type:
                    data_name: issue.type
                priorityName:
                    data_name: priority.priority
                resolutionName:
                    data_name: resolution.name
                reporterFullName:
                    data_name: reporterFullName
                assigneeFullName:
                    data_name: assigneeFullName
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
                step:
                    data_name: workflow_step.stepOrder
            default:
                updatedAt: DESC
        filters:
            columns:
                code:
                    type: string
                    data_name: issue.code
                summary:
                    type:      string
                    data_name: issue.summary
                type:
                    label: andy.bugtrack.issue.type.label
                    type: enum
                    enum_code: issue_type
                    data_name: issue.type
                collaborators:
                    type: entity
                    data_name: collaborators.id
                    options:
                        field_options:
                            class: OroUserBundle:User
                            translatable_options: false
                priorityName:
                    label: andy.bugtrack.issue.priority.label
                    type: entity
                    data_name: priority.name
                    options:
                        field_options:
                              class: AndyBugTrackBundle:Priority
                              multiple: true
                              property: name
                              translatable_options: false
                resolutionName:
                    type: string
                    data_name: issue.resolution
                reporterFullName:
                    type: string
                    data_name: issue.reporter
                assigneeFullName:
                    type: string
                    data_name: issue.assignee
                createdAt:
                    type:      datetime
                    data_name: issue.createdAt
                updatedAt:
                    type:      datetime
                    data_name: issue.updatedAt
        properties:
            id: ~
            owner: ~
            view_link:
                type: url
                route: issue_view
                params: [ id ]
            update_link:
                type: url
                route: issue_update
                params: [ id ]
            delete_link:
                type: url
                route: issue_delete
                params: [ id ]
        actions:
            view_issue:
                type:          navigate
                acl_resource:  issue_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update_issue:
                type:          navigate
                acl_resource:  issue_create
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete_issue:
                type:          delete
                acl_resource:  issue_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link
    subtask-issues-grid:
        extends: issues-grid
        source:
            query:
                where:
                    and:
                        - issue.parentIssue = :parentId
            bind_parameters:
                - parentId
        filters: ~
        options:
            toolbarOptions:
                hide: true
    related-issues-grid:
        extends: issues-grid
        source:
            query:
                where:
                    and:
                        - :id MEMBER OF issue.relatedIssues
            bind_parameters:
                - id
        filters: ~
        options:
            toolbarOptions:
                hide: true
    user-issues-grid:
        extends: issues-grid
        source:
            query:
                where:
                    and:
                        - issue.assignee = :userId or issue.reporter = :userId
            bind_parameters:
                - userId
        filters: ~
        options:
            toolbarOptions:
                hide: true

    collaborators-grid:
        extends: users-grid
        source:
            query:
                where:
                    and:
                        - u.id = collaborators.id
                join:
                    inner:
                        -
                            join: AndyBugTrackBundle:Issue
                            alias: issue
                            conditionType: WITH
                            condition: "issue.id = :id"
                    left:
                        -   { join: issue.collaborators, alias: collaborators }
            bind_parameters:
                - id
        filters: ~
        options:
            toolbarOptions:
                hide: true
