parameters:
    issue.entity.class: Andy\Bundle\BugTrackBundle\Entity\Issue
    resolution.entity.class: Andy\Bundle\BugTrackBundle\Entity\Resolution

services:
    andy_bug_track.handler.issue_handler:
        class: Andy\Bundle\BugTrackBundle\Handler\IssueHandler
        arguments:
            - "@security.token_storage"
            - "@oro_entity.doctrine_helper"

    andy_bug_track.subtask_parent.validator:
        class: Andy\Bundle\BugTrackBundle\Validator\Constraints\ParentSubtaskValidator
        tags:
            - { name: validator.constraint_validator, alias: tracker_subtask_parent_validator }
