parameters:
    issue.entity.class: Andy\Bundle\BugTrackBundle\Entity\Issue
    resolution.entity.class: Andy\Bundle\BugTrackBundle\Entity\Resolution

services:
    andy_bug_track.handler.issue_handler:
        class: Andy\Bundle\BugTrackBundle\Handler\IssueHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"

