Andy\Bundle\BugTrackBundle\Entity\Issue:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [ code ]
            message: Sorry, this code is already in use
        - Andy\Bundle\BugTrackBundle\Validator\Constraints\ParentSubtask: ~
    properties:
        code:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
        summary:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
